apiVersion: apps/v1      
kind: StatefulSet        
metadata:
  name: "{{ .Values.db.name }}"
spec:      
  serviceName: "{{ .Values.db.name }}"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.db.label }}"
  template:              
    metadata:
      labels:
        app: "{{ .Values.db.label }}"
    spec:
      containers:
      - name: "{{ .Values.db.name }}-container"
        image: "{{ .Values.db.image }}"
        ports:
        - containerPort: {{ .Values.db.port }}
        env:                  
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "{{ .Values.db.password }}"