apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}"
spec:
  selector:
    app: "{{ .Values.frontend.label }}"
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: NodePort