apiVersion: v1
kind: Service
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  ports:
  - port: 5432
  selector:
    app: sonarqube-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-db
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube-db
  template:
    metadata:
      labels:
        app: sonarqube-db
    spec:
      containers:
      - name: postgres
        image: bitnami/postgresql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: "sonarpass"
        - name: POSTGRES_DB
          value: "sonar"
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:community
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
        - name: SONAR_JDBC_URL
          value: "jdbc:postgresql://sonarqube-db:5432/sonar"
        - name: SONAR_JDBC_USERNAME
          value: "postgres"
        - name: SONAR_JDBC_PASSWORD
          value: "sonarpass"