# Build stage
FROM node:20-alpine AS build
WORKDIR /app

COPY HelloFrontend/package*.json ./
RUN npm install

COPY HelloFrontend/. .
RUN npm run build -- --configuration development

# Nginx stage
FROM nginx:alpine
COPY --from=build /app/dist/hello-frontend/browser/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]